import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import Link from 'next/link'

async function approveDevelopment(id: string) {
  'use server'
  const supabase = await createClient()
  await supabase.from('developments').update({ review_status: 'approved', is_public: false }).eq('id', id)
  revalidatePath('/admin/review')
}

async function rejectDevelopment(id: string) {
  'use server'
  const supabase = await createClient()
  await supabase.from('developments').update({ review_status: 'rejected' }).eq('id', id)
  revalidatePath('/admin/review')
}

async function approveAllDevelopments(ids: string[]) {
  'use server'
  const supabase = await createClient()
  await supabase.from('developments').update({ review_status: 'approved', is_public: false }).in('id', ids)
  revalidatePath('/admin/review')
  redirect('/admin/review')
}

async function approveArticle(id: string) {
  'use server'
  const supabase = await createClient()
  await supabase.from('articles').update({ review_status: 'approved' }).eq('id', id)
  revalidatePath('/admin/review')
}

async function rejectArticle(id: string) {
  'use server'
  const supabase = await createClient()
  await supabase.from('articles').update({ review_status: 'rejected' }).eq('id', id)
  revalidatePath('/admin/review')
}

async function approveBriefing(id: string) {
  'use server'
  const supabase = await createClient()
  await supabase.from('briefings').update({ review_status: 'approved' }).eq('id', id)
  revalidatePath('/admin/review')
}

async function rejectBriefing(id: string) {
  'use server'
  const supabase = await createClient()
  await supabase.from('briefings').update({ review_status: 'rejected' }).eq('id', id)
  revalidatePath('/admin/review')
}

export default async function AdminReviewPage() {
  const supabase = await createClient()

  const [{ data: pendingDevs }, { data: pendingBriefings }, { data: pendingArticles }] = await Promise.all([
    supabase
      .from('developments')
      .select('id, title_en, body_en, category, date, source, source_url')
      .eq('ai_generated', true)
      .eq('review_status', 'pending')
      .order('created_at', { ascending: false }),
    supabase
      .from('briefings')
      .select('id, title_en, summary_en, body_en, published_date')
      .eq('ai_generated', true)
      .eq('review_status', 'pending')
      .order('created_at', { ascending: false }),
    supabase
      .from('articles')
      .select('id, title, slug, excerpt, body, keywords, published_date, read_time_mins, title_vi, excerpt_vi, body_vi, keywords_vi')
      .eq('ai_generated', true)
      .eq('review_status', 'pending')
      .order('created_at', { ascending: false }),
  ])

  const totalPending = (pendingDevs?.length ?? 0) + (pendingBriefings?.length ?? 0) + (pendingArticles?.length ?? 0)
  const devIds = (pendingDevs ?? []).map(d => d.id as string)

  return (
    <div className="space-y-8">

      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-navy">AI Draft Review</h1>
          <p className="text-sm text-navy/50 mt-1">Content generated by Claude — review before publishing</p>
        </div>
        {totalPending > 0 && (
          <span className="flex-shrink-0 text-xs font-bold bg-accent text-white rounded-full px-3 py-1.5 mt-1">
            {totalPending} pending
          </span>
        )}
      </div>

      {totalPending === 0 && (
        <div className="bg-white rounded-2xl border border-navy/8 px-6 py-16 text-center">
          <p className="text-3xl mb-3">&#10003;</p>
          <p className="text-base font-semibold text-navy/50">All caught up — no drafts pending review</p>
          <p className="text-sm text-navy/35 mt-1">Claude will generate new drafts on the monthly schedule</p>
        </div>
      )}

      {/* Developments */}
      {pendingDevs && pendingDevs.length > 0 && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-bold text-navy">
              Developments <span className="text-sm font-normal text-navy/40">({pendingDevs.length})</span>
            </h2>
            {pendingDevs.length > 1 && (
              <form action={approveAllDevelopments.bind(null, devIds)}>
                <button type="submit" className="text-sm font-semibold rounded-lg px-4 py-2 bg-emerald-600 text-white hover:bg-emerald-700 transition-colors">
                  Approve all {pendingDevs.length}
                </button>
              </form>
            )}
          </div>
          <div className="space-y-3">
            {pendingDevs.map((d) => {
              const approveAction = approveDevelopment.bind(null, d.id as string)
              const rejectAction  = rejectDevelopment.bind(null, d.id as string)
              return (
                <div key={d.id as string} className="bg-white rounded-xl border border-navy/8 overflow-hidden">
                  <div className="h-0.5 bg-gradient-to-r from-accent to-purple-400" />
                  <div className="p-5">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-xs font-bold text-accent uppercase tracking-widest">AI Draft</span>
                      {d.category && <span className="text-xs font-semibold bg-navy/6 text-navy/50 rounded-full px-2 py-0.5">{d.category as string}</span>}
                      {d.date && <span className="text-xs text-navy/35">{new Date(d.date as string).toLocaleDateString()}</span>}
                    </div>
                    <h3 className="text-sm font-bold text-navy leading-snug mb-2">{d.title_en as string}</h3>
                    {d.body_en && <p className="text-sm text-navy/60 leading-relaxed mb-3">{d.body_en as string}</p>}
                    {d.source_url && (
                      <a href={d.source_url as string} target="_blank" rel="noopener noreferrer" className="text-xs text-accent hover:underline block mb-4">
                        Source: {(d.source as string) ?? d.source_url as string}
                      </a>
                    )}
                    <div className="flex items-center gap-3 pt-3 border-t border-navy/6">
                      <form action={approveAction}>
                        <button type="submit" className="rounded-lg px-4 py-2 text-sm font-semibold bg-emerald-600 text-white hover:bg-emerald-700 transition-colors">Approve</button>
                      </form>
                      <Link href={`/admin/developments/${d.id}/edit`} className="rounded-lg px-4 py-2 text-sm font-semibold bg-white border border-navy/15 text-navy hover:bg-navy/5 transition-colors">Edit first</Link>
                      <form action={rejectAction}>
                        <button type="submit" className="rounded-lg px-4 py-2 text-sm font-semibold text-red-400 hover:text-red-600 transition-colors">Reject</button>
                      </form>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Briefings */}
      {pendingBriefings && pendingBriefings.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-lg font-bold text-navy">Briefing Drafts <span className="text-sm font-normal text-navy/40">({pendingBriefings.length})</span></h2>
          <div className="space-y-3">
            {pendingBriefings.map((b) => {
              const approveAction = approveBriefing.bind(null, b.id as string)
              const rejectAction  = rejectBriefing.bind(null, b.id as string)
              return (
                <div key={b.id as string} className="bg-white rounded-xl border border-navy/8 overflow-hidden">
                  <div className="h-0.5 bg-gradient-to-r from-accent to-purple-400" />
                  <div className="p-5">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-xs font-bold text-accent uppercase tracking-widest">AI Draft</span>
                      {b.published_date && <span className="text-xs text-navy/35">{new Date(b.published_date as string).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</span>}
                    </div>
                    <h3 className="text-base font-bold text-navy leading-snug mb-2">{b.title_en as string}</h3>
                    {b.summary_en && <p className="text-sm text-navy/60 leading-relaxed mb-3">{b.summary_en as string}</p>}
                    {b.body_en && (
                      <div className="bg-navy/2 rounded-lg p-3 mb-4 max-h-48 overflow-y-auto">
                        <pre className="text-xs text-navy/60 whitespace-pre-wrap font-sans leading-relaxed">{b.body_en as string}</pre>
                      </div>
                    )}
                    <div className="flex items-center gap-3 pt-3 border-t border-navy/6">
                      <form action={approveAction}>
                        <button type="submit" className="rounded-lg px-4 py-2 text-sm font-semibold bg-emerald-600 text-white hover:bg-emerald-700 transition-colors">Approve</button>
                      </form>
                      <Link href={`/admin/briefings/${b.id}/edit`} className="rounded-lg px-4 py-2 text-sm font-semibold bg-white border border-navy/15 text-navy hover:bg-navy/5 transition-colors">Edit first</Link>
                      <form action={rejectAction}>
                        <button type="submit" className="rounded-lg px-4 py-2 text-sm font-semibold text-red-400 hover:text-red-600 transition-colors">Reject</button>
                      </form>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Articles */}
      {pendingArticles && pendingArticles.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-lg font-bold text-navy">Articles <span className="text-sm font-normal text-navy/40">({pendingArticles.length})</span></h2>
          <div className="space-y-3">
            {pendingArticles.map((a) => {
              const approveAction = approveArticle.bind(null, a.id as string)
              const rejectAction  = rejectArticle.bind(null, a.id as string)
              return (
                <div key={a.id as string} className="bg-white rounded-xl border border-navy/8 overflow-hidden">
                  <div className="h-0.5 bg-gradient-to-r from-accent to-purple-400" />
                  <div className="p-5">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-xs font-bold text-accent uppercase tracking-widest">AI Draft</span>
                      {a.read_time_mins && <span className="text-xs text-navy/35">{a.read_time_mins} min read</span>}
                      <span className="text-xs font-semibold bg-blue-50 text-blue-700 rounded-full px-2 py-0.5">EN</span>
                      {a.body_vi
                        ? <span className="text-xs font-semibold bg-emerald-50 text-emerald-700 rounded-full px-2 py-0.5">VI ready</span>
                        : <span className="text-xs font-semibold bg-navy/6 text-navy/40 rounded-full px-2 py-0.5">VI missing</span>
                      }
                    </div>
                    <h3 className="text-base font-bold text-navy leading-snug mb-1">{a.title as string}</h3>
                    <p className="text-xs text-navy/35 font-mono mb-3">/articles/{a.slug as string}</p>

                    {a.excerpt && <p className="text-sm text-navy/60 leading-relaxed mb-2">{a.excerpt as string}</p>}
                    {a.keywords && (
                      <div className="flex flex-wrap gap-1.5 mb-3">
                        {(a.keywords as string).split(',').map(k => (
                          <span key={k} className="text-xs bg-accent/8 text-accent/70 rounded-full px-2 py-0.5">{k.trim()}</span>
                        ))}
                      </div>
                    )}
                    {a.body && (
                      <div className="bg-navy/2 rounded-lg p-3 mb-3 max-h-32 overflow-y-auto">
                        <p className="text-xs font-semibold text-navy/40 mb-1">English preview</p>
                        <pre className="text-xs text-navy/55 whitespace-pre-wrap font-sans leading-relaxed">{(a.body as string).slice(0, 400)}{(a.body as string).length > 400 ? '...' : ''}</pre>
                      </div>
                    )}
                    {a.body_vi && (
                      <div className="bg-emerald-50/60 rounded-lg p-3 mb-4 max-h-32 overflow-y-auto border border-emerald-100">
                        <p className="text-xs font-semibold text-emerald-700 mb-1">{(a.title_vi as string) || 'Vietnamese version'}</p>
                        {a.excerpt_vi && <p className="text-xs text-navy/55 mb-1 italic">{a.excerpt_vi as string}</p>}
                        <pre className="text-xs text-navy/55 whitespace-pre-wrap font-sans leading-relaxed">{(a.body_vi as string).slice(0, 300)}{(a.body_vi as string).length > 300 ? '...' : ''}</pre>
                      </div>
                    )}

                    <div className="flex items-center gap-3 pt-3 border-t border-navy/6">
                      <form action={approveAction}>
                        <button type="submit" className="rounded-lg px-4 py-2 text-sm font-semibold bg-emerald-600 text-white hover:bg-emerald-700 transition-colors">Approve</button>
                      </form>
                      <Link href={`/admin/articles/${a.id}/edit`} className="rounded-lg px-4 py-2 text-sm font-semibold bg-white border border-navy/15 text-navy hover:bg-navy/5 transition-colors">Edit first</Link>
                      <form action={rejectAction}>
                        <button type="submit" className="rounded-lg px-4 py-2 text-sm font-semibold text-red-400 hover:text-red-600 transition-colors">Reject</button>
                      </form>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

    </div>
  )
}
