-- Add AI draft tracking columns to developments and briefings
-- These allow Claude to create pending drafts that the admin reviews before publishing

ALTER TABLE public.developments
  ADD COLUMN IF NOT EXISTS ai_generated   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS review_status  TEXT    NOT NULL DEFAULT 'approved';
-- review_status: 'pending' | 'approved' | 'rejected'

ALTER TABLE public.briefings
  ADD COLUMN IF NOT EXISTS ai_generated   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS review_status  TEXT    NOT NULL DEFAULT 'approved';

-- Index for fast pending draft queries
CREATE INDEX IF NOT EXISTS idx_developments_review ON public.developments (review_status, ai_generated);
CREATE INDEX IF NOT EXISTS idx_briefings_review    ON public.briefings    (review_status, ai_generated);

-- Comments
COMMENT ON COLUMN public.developments.ai_generated  IS 'True when this record was generated by Claude';
COMMENT ON COLUMN public.developments.review_status IS 'pending = awaiting admin review, approved = published, rejected = discarded';
COMMENT ON COLUMN public.briefings.ai_generated     IS 'True when this record was generated by Claude';
COMMENT ON COLUMN public.briefings.review_status    IS 'pending = awaiting admin review, approved = published, rejected = discarded';
